let products = [
  {
    title: `Audi R8`,
    price: 100000,
    stock: 3,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362281/Audi-R8_r96wpm.webp",
  },
  {
    title: `Audi A3`,
    price: 100000,
    stock: 10,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362281/Audi-A3_ex4gfh.jpg",
  },
  {
    title: `Audi S3`,
    price: 100000,
    stock: 5,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362281/Audi-S3_bjwrq9.jpg",
  },
  {
    title: `Audi RS7`,
    price: 100000,
    stock: 8,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362281/Audi-RS7_vyjndq.jpg",
  },
  {
    title: `Audi RS GT`,
    price: 100000,
    stock: 4,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362280/Audi-RS-GT_z2qtyc.jpg",
  },
  {
    title: `Audi RS5`,
    price: 100000,
    stock: 12,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362280/Audi-RS5_qal56o.jpg",
  },
  {
    title: `Audi A7`,
    price: 100000,
    stock: 6,
    description: `elegante auto`,
    category: `deportivo`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362280/Audi-A7_tp7r9b.jpg",
  },
  {
    title: `Audi Q7`,
    price: 100000,
    stock: 15,
    description: `elegante auto`,
    category: `camionetas`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362280/Audi-Q7_jxyted.jpg",
  },
  {
    title: `Audi E-tron`,
    price: 100000,
    stock: 1,
    description: `elegante auto`,
    category: `camionetas`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362280/Audi-E-tron_h7esuk.jpg",
  },
  {
    title: `Audi Q8`,
    price: 100000,
    stock: 21,
    description: `elegante auto`,
    category: `camionetas`,
    img: "https://res.cloudinary.com/dnm34qgtv/image/upload/v1687362280/Audi-Q8_fbg6zv.jpg",
  },
];

export default products
